name: CI

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'
          - 'head'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Compile
        run: bundle exec rake compile
      - name: Test
        run: bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: RuboCop
        run: bundle exec rubocop

  ci:
    runs-on: ubuntu-latest
    name: CI
    needs: [test, lint]
    if: always()
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.test.result }}" != "success" || "${{ needs.lint.result }}" != "success" ]]; then
            echo "Test result: ${{ needs.test.result }}"
            echo "Lint result: ${{ needs.lint.result }}"
            exit 1
          fi
